#!/usr/bin/env bash
set -e
set -u
set -o pipefail
shopt -s globstar

runner=$0

run() {
  go run *[^_test].go $@
}

run_watch() {
  rg --files-with-matches "" | entr -c $runner run $@
}

build() {
  go build -o gisp $@
}

test() {
  go test ./... $@
}

test_nocache() {
  test -count=1 $@
}

test_watch() {
  rg --files-with-matches "" | entr -c $runner test $@
}

default() {
  test_nocache
  build
}

tasks() {
  local task=${1:-""}
  shift || true
  case $task in
  run)
    run $@
    ;;
  run:watch)
    run_watch $@
    ;;
  build)
    build $@
    ;;
  test)
    test $@
    ;;
  test:nocache)
    test_nocache $@
    ;;
  test:watch)
    test_watch $@
    ;;
  "")
    default
    ;;
  *)
    echo "No tasks defined for \"$task\""
    ;;
  esac
}

total_time() {
  TIMEFORMAT="Total time: %Rs"
  time $@
  unset TIMEFORMAT
}

total_time tasks $@
