#!/usr/bin/env bash
set -e
set -u
set -o pipefail
shopt -s globstar

runner=$0

run() {
  go run *[^_test].go
}

run_watch() {
  rg --files-with-matches "" | entr $runner run
}

build() {
  go build -o gisp
}

test() {
  go test ./...
}

test_watch() {
  rg --files-with-matches "" | entr $runner test
}

default() {
  test
  build
}

tasks() {
  case ${1:-""} in
  run)
    run
    ;;
  run:watch)
    run_watch
    ;;
  build)
    build
    ;;
  test)
    test
    ;;
  test:watch)
    test_watch
    ;;
  "")
    default
    ;;
  *)
    echo "No tasks defined for $1"
    ;;
  esac
}

total_time() {
  TIMEFORMAT="Total time: %Rs"
  time $@
  unset TIMEFORMAT
}

total_time tasks ${1:-""}
